#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+TITLE: Org-clock-convenience
#+DATE: <2016-01-09 Sat>
#+AUTHOR: Derek Feichtinger
#+EMAIL: dfeich@gmail.com
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 8.3.2)

* Introduction

  This is a collection of functions I am writing in order to make my
  clocking workflows easier. It's not ready for publishing to MELPA.

  It happens quite often that I get distracted by other tasks while
  being clocked in. At the end of a day when I need to fill the gaps
  and get the clocking consistent, I have to constantly jump between
  the agenda view with the log lines (to see the surrounding tasks log
  lines) and the org agenda file's clock lines in order to apply
  changes.

  I always wanted to have commands with which I can change the clock
  values directly *from the log lines in the agenda view* in the same
  way that one can change timestamps under the cursor inside of an org
  file using =org-timestamp-up= and =org-timestamp-down= (usually
  mapped to =<S-up>= and =<S-down>=).

  Some of the available interactive functions
  - =org-clock-conv-timestamp-up= and =org-clock-conv-timestamp-down=:
    When on a /clocked/ line in the agenda buffer, this function will
    increase/decrease the time according to the position of the
    cursor. If the cursor is on the hour field, change the hour. If it
    is on the minutes field, change the minutes. Undo works on the
    agenda and on the source buffer.
  - =org-clock-conv-goto-ts= goto the associated timestamp in the org
    file. Position the cursor respective to where the cursor was
    placed in the agenda view (e.g. on the minutes part of the
    starting time).
  - =org-clock-conv-goto-last-clockout=: goto timestamp of the last
    clockout (this is based on a real search through the buffer and
    not based on the saved clockout value).

* Current shortcomings
  - When changing the logged times using =org-clock-conv-timestamp-up=
    and =org-clock-conv-timestamp-down=, the changes are now indicated
    by a special font to display the changed fields. The agenda view
    is only rebuilt upon user request (using =g= or =r=). For some
    reason currently two rebuilds are needed before the agenda view is
    updated. The first one does not seem to take effect. This is a
    minor invonvenience.
     
  
